In [53]:
import pandas as pd

In [54]:
#Creating the Dataset
data = {
    "Tid": [1,2,3,4,5,6,7,8,9,10],
    "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
    "Marital Status": ["Single", "Married", "Single", "Married", "Divorced", "Married", "Divorced", "Single", "Married", "Single"],
    "Taxable Income": [125000, 100000, 70000, 120000, 95000, 60000, 220000, 85000, 75000, 90000],
    "Cheat":["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
    }

df = pd.DataFrame(data)
df

   Tid Refund Marital Status  Taxable Income Cheat
0    1    Yes         Single          125000    No
1    2     No        Married          100000    No
2    3     No         Single           70000    No
3    4    Yes        Married          120000    No
4    5     No       Divorced           95000   Yes
5    6     No        Married           60000    No
6    7    Yes       Divorced          220000    No
7    8     No         Single           85000   Yes
8    9     No        Married           75000    No
9   10     No         Single           90000   Yes

Q2. From the above table that you have created, locate row 0, 4, 7 and 8 using DataFrame.

In [55]:
df.loc[[0,4,7,8]]

   Tid Refund Marital Status  Taxable Income Cheat
0    1    Yes         Single          125000    No
4    5     No       Divorced           95000   Yes
7    8     No         Single           85000   Yes
8    9     No        Married           75000    No

Q3. i) Select row from index 3 to 7.

In [56]:
df.loc[3:7]

   Tid Refund Marital Status  Taxable Income Cheat
3    4    Yes        Married          120000    No
4    5     No       Divorced           95000   Yes
5    6     No        Married           60000    No
6    7    Yes       Divorced          220000    No
7    8     No         Single           85000   Yes

Q3. ii) Select row from index 4 to 8, and column 2 to 4.

In [57]:
df.iloc[4:9, 1:4]

  Refund Marital Status  Taxable Income
4     No       Divorced           95000
5     No        Married           60000
6    Yes       Divorced          220000
7     No         Single           85000
8     No        Married           75000

Q3 iii) Select all rows with column index 1 to 3 (include index 3 during selection).

In [58]:
df.iloc[0:10, 1:4]

  Refund Marital Status  Taxable Income
0    Yes         Single          125000
1     No        Married          100000
2     No         Single           70000
3    Yes        Married          120000
4     No       Divorced           95000
5     No        Married           60000
6    Yes       Divorced          220000
7     No         Single           85000
8     No        Married           75000
9     No         Single           90000

Q.4 Read a csv file and display its first five rows.

In [59]:
df = pd.read_csv("Iris.csv")
df.loc[0:4]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Q.5 From the csv file (uploaded in the Q.4) delete row 4, and delete column 3. Display the
result.

In [60]:
df = df.drop(4)
df = df.drop(columns=["PetalLengthCm"])
df

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]

Q.6 Create a sample dataset (employees.csv) containing information about employees in
a company.

In [61]:
import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Ethan", "Frank", "Grace"],
    "Age": [25, 30, 35, 28, 40, 32, 24],
    "Department": ["IT", "HR", "IT", "Finance", "IT", "HR", "Finance"],
    "Experience": [2, 7, 10, 4, 12, 6, 1],
    "Salary": [50000, 65000, 80000, 60000, 90000, 70000, 45000],
    "Bonus": [5000, 7000, 10000, 6000, 12000, 8000, 4000],
    "Performance_Rating": [4.5, 4.0, 4.8, 3.8, 4.9, 4.2, 3.5]
}

df = pd.DataFrame(data)

# Save as CSV
df.to_csv("employees.csv", index=False)

print(df)

   Employee_ID     Name  Age Department  Experience  Salary  Bonus  \
0          101    Alice   25         IT           2   50000   5000
1          102      Bob   30         HR           7   65000   7000
2          103  Charlie   35         IT          10   80000  10000
3          104    Diana   28    Finance           4   60000   6000
4          105    Ethan   40         IT          12   90000  12000
5          106    Frank   32         HR           6   70000   8000
6          107    Grace   24    Finance           1   45000   4000

   Performance_Rating
0                 4.5
1                 4.0
2                 4.8
3                 3.8
4                 4.9
5                 4.2
6                 3.5

In [62]:
import pandas as pd

df = pd.read_csv("employees.csv")

df

,Employee_ID,Name,Age,Department,Experience,Salary,Bonus,Performance_Rating
0,101,Alice,25,IT,2,50000,5000,4.5
1,102,Bob,30,HR,7,65000,7000,4.0
2,103,Charlie,35,IT,10,80000,10000,4.8
3,104,Diana,28,Finance,4,60000,6000,3.8
4,105,Ethan,40,IT,12,90000,12000,4.9
5,106,Frank,32,HR,6,70000,8000,4.2
6,107,Grace,24,Finance,1,45000,4000,3.5

In [63]:
print("Shape:", df.shape)

Shape: (7, 8)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         7 non-null      int64
 1   Name                7 non-null      object
 2   Age                 7 non-null      int64
 3   Department          7 non-null      object
 4   Experience          7 non-null      int64
 5   Salary              7 non-null      int64
 6   Bonus               7 non-null      int64
 7   Performance_Rating  7 non-null      float64
dtypes: float64(1), int64(5), object(2)
memory usage: 580.0+ bytes

In [65]:
df.describe()

,Employee_ID,Age,Experience,Salary,Bonus,Performance_Rating
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,104.000000,30.571429,6.000000,65714.285714,7428.571429,4.242857
std,2.160247,5.652644,4.041452,15923.926293,2819.996623,0.519157
min,101.000000,24.000000,1.000000,45000.000000,4000.000000,3.500000
25%,102.500000,26.500000,3.000000,55000.000000,5500.000000,3.900000
50%,104.000000,30.000000,6.000000,65000.000000,7000.000000,4.200000
75%,105.500000,33.500000,8.500000,75000.000000,9000.000000,4.650000
max,107.000000,40.000000,12.000000,90000.000000,12000.000000,4.900000

In [66]:
df.head(5)
df.tail(3)

,Employee_ID,Name,Age,Department,Experience,Salary,Bonus,Performance_Rating
4,105,Ethan,40,IT,12,90000,12000,4.9
5,106,Frank,32,HR,6,70000,8000,4.2
6,107,Grace,24,Finance,1,45000,4000,3.5

In [67]:
average_salary = df["Salary"].mean()
print("Average Salary:", average_salary)

Average Salary: 65714.28571428571

In [68]:
total_bonus = df["Bonus"].sum()
print("Total Bonus:", total_bonus)

Total Bonus: 52000

In [69]:
youngest_age = df["Age"].min()
print("Youngest Age:", youngest_age)

Youngest Age: 24

In [70]:
highest_rating = df["Performance_Rating"].max()
print("Highest Performance Rating:", highest_rating)

Highest Performance Rating: 4.9

In [71]:
df = df.sort_values(by="Salary", ascending=False)

df

,Employee_ID,Name,Age,Department,Experience,Salary,Bonus,Performance_Rating
4,105,Ethan,40,IT,12,90000,12000,4.9
2,103,Charlie,35,IT,10,80000,10000,4.8
5,106,Frank,32,HR,6,70000,8000,4.2
1,102,Bob,30,HR,7,65000,7000,4.0
3,104,Diana,28,Finance,4,60000,6000,3.8
0,101,Alice,25,IT,2,50000,5000,4.5
6,107,Grace,24,Finance,1,45000,4000,3.5

In [72]:
def categorize(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

df["Performance_Category"] = df["Performance_Rating"].apply(categorize)

df

,Employee_ID,Name,Age,Department,Experience,Salary,Bonus,Performance_Rating,Performance_Category
4,105,Ethan,40,IT,12,90000,12000,4.9,Excellent
2,103,Charlie,35,IT,10,80000,10000,4.8,Excellent
5,106,Frank,32,HR,6,70000,8000,4.2,Good
1,102,Bob,30,HR,7,65000,7000,4.0,Good
3,104,Diana,28,Finance,4,60000,6000,3.8,Average
0,101,Alice,25,IT,2,50000,5000,4.5,Excellent
6,107,Grace,24,Finance,1,45000,4000,3.5,Average

In [73]:
print(df.isnull().sum())
print(df.isnull().any())

Employee_ID             0
Name                    0
Age                     0
Department              0
Experience              0
Salary                  0
Bonus                   0
Performance_Rating      0
Performance_Category    0
dtype: int64
Employee_ID             False
Name                    False
Age                     False
Department              False
Experience              False
Salary                  False
Bonus                   False
Performance_Rating      False
Performance_Category    False
dtype: bool

In [74]:
df = df.rename(columns={"Employee_ID": "ID"})

df

,ID,Name,Age,Department,Experience,Salary,Bonus,Performance_Rating,Performance_Category
4,105,Ethan,40,IT,12,90000,12000,4.9,Excellent
2,103,Charlie,35,IT,10,80000,10000,4.8,Excellent
5,106,Frank,32,HR,6,70000,8000,4.2,Good
1,102,Bob,30,HR,7,65000,7000,4.0,Good
3,104,Diana,28,Finance,4,60000,6000,3.8,Average
0,101,Alice,25,IT,2,50000,5000,4.5,Excellent
6,107,Grace,24,Finance,1,45000,4000,3.5,Average

In [75]:
employees_experience = df[df["Experience"] > 5]

print(employees_experience)

it_employees = df[df["Department"] == "IT"]

print(it_employees)

    ID     Name  Age Department  Experience  Salary  Bonus  \
4  105    Ethan   40         IT          12   90000  12000
2  103  Charlie   35         IT          10   80000  10000
5  106    Frank   32         HR           6   70000   8000
1  102      Bob   30         HR           7   65000   7000

   Performance_Rating Performance_Category
4                 4.9            Excellent
2                 4.8            Excellent
5                 4.2                 Good
1                 4.0                 Good
    ID     Name  Age Department  Experience  Salary  Bonus  \
4  105    Ethan   40         IT          12   90000  12000
2  103  Charlie   35         IT          10   80000  10000
0  101    Alice   25         IT           2   50000   5000

   Performance_Rating Performance_Category
4                 4.9            Excellent
2                 4.8            Excellent
0                 4.5            Excellent

In [76]:
df["Tax"] = df["Salary"] * 0.10

df

,ID,Name,Age,Department,Experience,Salary,Bonus,Performance_Rating,Performance_Category,Tax
4,105,Ethan,40,IT,12,90000,12000,4.9,Excellent,9000.0
2,103,Charlie,35,IT,10,80000,10000,4.8,Excellent,8000.0
5,106,Frank,32,HR,6,70000,8000,4.2,Good,7000.0
1,102,Bob,30,HR,7,65000,7000,4.0,Good,6500.0
3,104,Diana,28,Finance,4,60000,6000,3.8,Average,6000.0
0,101,Alice,25,IT,2,50000,5000,4.5,Excellent,5000.0
6,107,Grace,24,Finance,1,45000,4000,3.5,Average,4500.0

In [77]:
df.to_csv("employees_modified.csv", index=False)

print("File saved successfully!")

File saved successfully!